name: pinput
description: Flutter package to create Pin code input text field with every pixel customization possibility and beautiful animations
version: 1.0.0
homepage: https://tkko.github.io/Flutter_PinPut
repository: https://github.com/Tkko/Flutter_PinPut


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
